# Generated by Django 5.2.9 on 2026-01-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('details', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='story_tips/')),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
