# Generated by Django 5.2.9 on 2026-01-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ads_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ads_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ads_link',
            field=models.URLField(blank=True),
        ),
    ]
