# Generated by Django 5.2.9 on 2025-12-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_name_alter_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='counted_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
